import { TextDivider } from "components/TextDivider/TextDivider"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.sass"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.hero}>
          <div className={styles.content}>
            <h1>
              <span>Shred</span>
              <span>quarters</span>
            </h1>
            <p>
              An all-inclusive skate club focused primarily on skateboarding and
              longboarding, but open to anything on wheels! Meet fellow
              shredders in an inclusive, social, and community-oriented club
              right here on the Virginia Tech campus.
            </p>
          </div>
          <div className={styles.iso_truck}>
            <Image
              src={"/img/truck_iso.svg"}
              layout="responsive"
              width="64"
              height="64"
              alt="hero_blob"
            />
          </div>
        </section>
        <TextDivider header="The Mission" float={20} />
      </main>
    </div>
  )
}

export default Home
